services:
  pwa-soundboard:
    container_name: pwa-soundboard
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - ./data:/data
    environment:
      HOST: "${HOST:-0.0.0.0}"
      PORT: "${PORT:-3000}"
      ORIGIN: "${ORIGIN:-}"
      SAMPLES_DIR: /data/audio
      SAMPLES_JSON: /data/samples.json
    restart: unless-stopped
